apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dg1686lfr-python 
  janus-idp.io/tekton: dg1686lfr-python
  backstage.io/kubernetes-id: dg1686lfr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dg1686lfr-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml